import type { NextPage } from 'next'
import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import { MainLayout } from 'components/layout/MainLayout';
import { InvoicesList } from 'components/invoices/InvoicesList';
import { databaseService } from 'services/databaseService';
import { useRouter } from 'next/router'
import { InnerContentContainer } from 'components/layout/InnerContentContainer';
import { Typography } from "@mui/material";
import { currencyService } from 'services/currencyService';

const currency = new currencyService();

const Invoice = () => {
  const [invoices, setInvoice] = useState([]);
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    async function init(): Promise<void> {
      const dbResponse = databaseService.getInvoice(id);
      setInvoice(dbResponse);
      await currency.initialize();
    }
    init();
  }, [router]);
  return (
    <>
      <Head>
        <title>Invoice</title>
        <meta name="description" content="Invoices app Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout pageTitle={`Invoice ID: ${id ? id : ''}`} >
        <InnerContentContainer>
          <Typography>
            Concept: {invoices?.concept}
          </Typography>
        </InnerContentContainer>
        <InnerContentContainer>
          <Typography>
            Items list:
          </Typography>
          <InvoicesList
            invoices={invoices?.item}
            fields={[{ label: 'Name', key: 'name' }, { label: 'Amount', key: 'amount' }, { label: 'Description', key: 'description' }, { label: 'Currency', key: 'currency' }]}
            linkKey="id"
          />
        </InnerContentContainer>
        <InnerContentContainer>
          <Typography>
            Total MXN: { invoices?.total }
          </Typography>
          <Typography>
            Total USD: {currency.currencyData && currency.mxnToUsd(invoices?.total)}
          </Typography>
        </InnerContentContainer>
      </MainLayout>
    </>
  )
}

export default Invoice
