import type { NextPage } from 'next'
import Head from 'next/head'
import { MainLayout } from 'components/layout/MainLayout';
import CreateInvoiceForm from 'components/invoices/CreateInvoiceForm';

const CreateInvoice: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Invoices</title>
        <meta name="description" content="Invoices app Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout pageTitle="Create invoices" >
        <CreateInvoiceForm />
      </MainLayout>
    </>
  )
}

export default CreateInvoice
